language: go

branches:
  only:
    - master

go:
  - 1.6
  - tip

script:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter -i -u -f
  - gometalinter --exclude="(_test.go)" --deadline=1m ./...

matrix:
  allow_failures:
    - go: tip
