language: go
sudo: false

branches:
  only:
    - master

go:
  - 1.6
  - tip

script:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter -i -u -f
  - go install ./...
  - gometalinter --exclude="(_test.go|fakes)" --deadline=1m ./... --disable=aligncheck

matrix:
  allow_failures:
    - go: tip
