version: "{build}"

platform: x64

branches:
  only:
    - master

skip_tags: true

clone_folder: c:\gopath\src\github.com\joefitzgerald\inductor

environment:
  GOPATH: c:\gopath

  matrix:
  - GOVERSION: 1.6

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - go get -t -v ./...

build_script:
  - go build ./...
  - go test -v ./...

test: off
deploy: off
